name: Task
description: "Low level task or action that is often too granular for testing, but helps towards progress on an Epic or parent story"
labels: "B15.1,i&t.skip,task"
projects: "NASA-PDS/14"

body:
  - type: textarea
    id: description
    attributes:
      label: 💡 Description
      description: Enter description here. Make it detailed enough someone could actually know what you are doing, but if you spend too much time on this, it probably deserves it's own story.
      placeholder: Tell us what is up
    validations:
      required: true

  - type: textarea
    id: related
    attributes:
      label: ⚔️ Parent Epic / Related Tickets
      description: Associate parent Epic or related tickets here or select from ZenHub right sidebar.
