name: Task
description: "Low level task or action that is often too granular for testing, but helps towards progress on an Epic or parent story"
labels: "B15.1,i&t.skip,task"
projects: "NASA-PDS/14"

body:
  - type: checkboxes
    id: parent-task
    attributes:
      label: Parent issue set?
      description: From right panel, set parent issue. If one does not exist, create one.
      options:
        - label: Yes
          required: true

  - type: textarea
    id: description
    attributes:
      label: 💡 Description
      description: Enter description here. Make it detailed enough someone could actually know what you are doing, but if you spend too much time on this, it probably deserves it's own story.
      placeholder: Tell us what is up
    validations:
      required: true
